config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "static_pages#index"

  match '/rsvp', to: 'rsvps#new', as: :new_rsvp, via: :get
  post '/rsvp', to: 'rsvps#create', as: :rsvps
end

app/models/meal_choice.rb
class MealChoice < ActiveRecord::Base
  BEEF = 1
  FISH = 2
  VEGETARIAN = 3
  OTHER = 4
  has_many :rsvps
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :meal_choice

  validates :name, presence: true
  validates :meal_choice, presence: true, if: Proc.new { |rsvp| rsvp.attending? }
  validates :attending, inclusion: [true, false]

  scope :attending, -> { where(attending: true) }
  scope :not_attending, -> { where(attending: false) }

  scope :beef, -> { where(meal_choice_id: MealChoice::BEEF) }
  scope :fish, -> { where(meal_choice_id: MealChoice::FISH) }
  scope :vegetarian, -> { where(meal_choice_id: MealChoice::VEGETARIAN) }
  scope :other, -> { where(meal_choice_id: MealChoice::OTHER) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
 def new
   @rsvp = Rsvp.new
 end

 def create
   @rsvp = Rsvp.new(rsvp_params)
   if @rsvp.save
     redirect_to new_rsvp_url, flash: :success
   else
     flash_now!(:error)
     render('new')
   end
 end

 private

 def rsvp_params
   params.require(:rsvp).permit(:attending, :meal_choice_id, :dietary_restrictions, :name)
 end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeddingRsvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Rachel &amp; Tom's Wedding</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two|Calligraffitti' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.14/themes/css/cartodb.css" />
    <%= stylesheet_link_tag("static", media: "all", "data-turbolinks-track" => true) %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="http://libs.cartocdn.com/cartodb.js/v3/3.14/cartodb.js"></script>
    <%= javascript_include_tag("jquery.easytabs", "data-turbolinks-track" => true)%>
    <%= javascript_include_tag("static", "data-turbolinks-track" => true)%>
    <script>
      $(document).ready( function() {
        cartodb.createVis('map', 'https://treznick.cartodb.com/api/v2/viz/653b7a38-0214-11e5-acee-0e24745e8b53/viz.json', {
          center_lat: 41.2489134,
          center_lon: -72.9031886,
          zoom: 16
        });
      });
    </script>
  </body>
</html>

app/views/rsvps/new.html.erb
<div class="container-fluid">
  <div class="panel panel-default form-panel">
    <div class="panel-heading">
      <div class="text-center">
        <h1>RSVP Form</h1>
      </div>
    </div>
    <div class="panel-body">
      <div class="row">
        <div id="flash_messages">
          <%= flash_messages(:close, :fade) %>
        </div>
        <div class="panel">
          <p class="lead"><strong>Note:</strong> To properly record individual meal choices, please fill this form out once per guest.</p>
          <p>If you have any questions, or want to change your submissions, please email <a href="mailto:reznick.silbermann.wedding@gmail.com">reznick.silbermann.wedding@gmail.com</a></p>
        </div>
      </div>
      <div class="row">
        <%= simple_form_for(@rsvp, html: { class: 'form-horizontal'}) do |f| %>
          <%= f.input :name, wrapper_html: {class: 'form-group row col-sm-8 col-lg-8'}%>
          <%= f.input :attending, as: :radio_buttons, wrapper_html: {class: 'form-group row col-sm-8 col-lg-8'} %>
          <%= f.input :meal_choice_id, collection: MealChoice.all, as: :radio_buttons, label_method: :name, value_method: :id, wrapper_html: {class: 'form-group row col-sm-8 col-lg-8'} %>
          <%= f.input :dietary_restrictions, as: :text, wrapper_html: {class: 'form-group row col-sm-8 col-lg-8'} %>
          <div class='form-group row col-sm-8 col-lg-8'>
            <%= f.button :submit, "Save RSVP" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Home", root_path, class: "pull-right" %>
</div>

app/views/static_pages/index.html.erb
<a id="menu-toggle" href="#">
  <i class="fa fa-bars"></i>
</a>
<nav id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand text-center">
      <a href="#" id="menu-close">
        <i class="fa fa-times"></i>
      </a>
    </li>
    <li>
      <a href="#top">Home</a>
    </li>
    <li>
      <a href="#details">Details</a>
    </li>
    <li>
      <a href="#event">Transportation</a>
    </li>
    <li>
      <a href="#hotel">Hotels</a>
    </li>
    <li>
      <a href="#registry">Registry</a>
    </li>
    <li>
      <a href="#rsvp">RSVP</a>
    </li>
  </ul>
</nav>
<header id="top" class="header clearfix">
  <div class="carousel_banner">
    <h1 class="logo_top">
      <a href="#" class="site-header">Rachel &amp; Tom</a>
    </h1>
    <br>
    <div class="banner-line">
      <h2 class="site-header">
        July 12th, 2015 - Lighthouse Point Park - New Haven, CT
      </h2>
      <br>
    </div>
    <div class="top_arrow">
      <a href="#details">
        <i class="fa fa-chevron-down"></i>
      </a>
    </div>
  </div>
</header>
<section>
  <article class="details" id="details">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center ">
          <h1>Details</h1>
          <p class="big-text">Please join us on Sunday July 12th, 2015 at Lighthouse Point Park in New Haven, CT to celebrate our wedding!</p>
          <h2>Ceremony &amp; Reception</h2>
          <dl class="dl-horizontal">
            <dt><strong>Address</strong></dt><dd>
              <a href="https://www.google.com/maps/place/2+Lighthouse+Rd,+New+Haven,+CT+06512" target="_blank">
                <address>
                  2 Lighthouse Rd.<br>
                  New Haven, CT 06512
                </address>
              </a>
            </dd>
            <dt><strong>Ceremony</strong></dt><dd>5:30 PM, on the beach near the Lighthouse (weather permitting).</dd>
            <dt><strong>Reception</strong></dt><dd>Immediately following the ceremony, inside the Carousel Pavillion.</dd>
          </dl>
          <h2>The Next Morning</h2>
          <p>For those staying over in New Haven on Sunday night, please join us for a buffet breakfast on Monday morning, 9:00 - 11:00 AM at the <a href="https://www.google.com/maps/place/The+Study+at+Yale+Hotel" target="_blank">Study Hotel</a>, Gallery 1.
        </div>
      </div>
    </div>
  </article>
  <article class="rachel_tom">
    <div class="rachel_tom_parallax">
      <div class="rachel_tom_bottom_bg">
      </div>
    </div>
  </article>
  <article class="event" id="event">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Transportation &amp Parking</h1>
          <dl class="dl-horizontal">
            <dt>Shuttle</dt><dd>A shuttle will leave the Mariott Courtyard and the Study hotels at 5:00pm to go to Lighthouse Point. From 10:30 p.m. to 12:00 a.m., one bus will shuttle back and forth from Lighthouse Point to the hotels.</dd>
            <dt>Taxi</dt><dd>Call <a href="tel://203-777-7777">(203) 777-7777</a> for a cab.</dd>
            <dt>Parking</dt><dd>Parking is free for our guests. As you enter the Park continue straight after the ticket booth stop, following the green signs to 'Carousel parking.' Go right into the directed lot (surrounded by colored concrete blocks). Drive to the far end of the directed lot (the Lighthouse can be seen in the distance to your left), park your vehicle and walk to the <strong>Red Gate</strong> on the access road.</dd>
          </dl>
        </div>
      </div>
      <div class="row">
        <div id="map"></div>
      </div>
    </div>
  </article>
  <article class="lighthouse" id="lighthouse">
    <div class="lighthouse_parallax">
      <div class="lighthouse_bottom_parallax" id="email">
        <div class="lighthouse_bottom_bg">
        </div>
      </div>
    </div>
  </article>
  <article class="hotels" id="hotel">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Hotels</h1>
          <p class="big-text">We have reserved rooms at the following hotels</p>
          <address>
            <strong><a class="hotel-link" href="https://reservations.ihotelier.com/crs/g_reservation.cfm?groupID=1274823&hotelID=15472" target="_blank">The Study at Yale</a></strong><br>
            1157 Chapel Street<br>
            New Haven, CT 06511<br>
            <abbr title="Phone">P:</abbr> <a href="tel://203-503-3900">(203) 503-3900</a>
          </address>
          <address>
            <strong><span class="hotel-link">The Courtyard Marriott</span></strong><br>
            30 Whalley Avenue<br>
            New Haven, CT 06511<br>
            <abbr title="Phone">P:</abbr> <a href="tel://203-777-6221">(203) 777-6221</a>
          </address>
          <p class="big-text">Please reference the Silbermann-Reznick wedding when reserving rooms</p>
        </div>
      </div>
    </div>
  </article>
  <article class="couple_main">
    <div class="couple_main_parallax">
      <div class="couple_bottom_bg">
      </div>
    </div>
  </article>
  <article class="registry" id="registry">
    <div class="container">
      <h1>Registry</h1>
      <p class="big-text">We are registered at the following:</p>
      <div class="list-group">
        <a href="http://www.amazon.com/registry/wedding/1OPPQ4FRBRA9Z" class="hotel-link list-group-item"  target="_blank">Amazon</a>
        <a href="http://www.macys.com/registry/wedding/guest/?registryId=6333159" class="hotel-link list-group-item"  target="_blank">Macy's</a>
        <a href="http://www.rei.com/GiftRegistryDetails/GR111678846" class="hotel-link list-group-item"  target="_blank">REI</a>
        <a href="http://www.sokindregistry.org/registry/5909" class="hotel-link list-group-item" target="_blank">So Kind Registry</a>
      </div>
      <p class="big-text">Alternatively, please consider a donation to one of our favorite charities using the <a href="http://www.idofoundation.org/cgi-bin/viewdonations.cgi?OccasionID=166742" target="_blank">I Do Foundation</a></p>
    </div>
  </article>
  <article class="pavillion_main">
    <div class="pavillion_main_parallax">
      <div class="pavillion_bottom_bg">
      </div>
    </div>
  </article>
  <article class="rsvp" id="rsvp">
    <div class="container">
      <h1>R.S.V.P</h1>
      <%= link_to 'Click here to R.S.V.P', new_rsvp_path, class: "btn btn-default" %>
    </div>
  </article>
</section>
<footer>
  <div class="container">
    <div class="row">
      <p class="big-text">Made with <i class="fa fa-heart red"></i> in New Haven, CT</p>
    </div>
  </div>
</footer>